channels:
  - conda-forge
  - nodefaults
dependencies:
  #- git
  - ruby=3.3
  - c-compiler
  - cxx-compiler
  - make
  #- rb-bundler # This and *many* other ruby gems are out of date, use gem install bundler
  #- rb-github-pages # This and *many* other ruby gems are out of date, use bundle install
#Run:
# $ conda activate name-of-your-env
# $ gem install bundler
# $ bundle install